### ISSUE TITLE
目前可用的开发文档已丢失

### ISSUE THREAD

**Issue by Zervan29131** [Thaumy/pilipala#5]
快速入门：https://github.com/Thaumy/pilipala/blob/master/QuickStart.md
望尽快完成开发

**Comment by Thaumy** [comment]
hello！
抱歉，原有的教程是面向pilipala beta9的早期版本编写的，由于后期采用了不同的设计思想，为避免产生误导，已经将教程从分支中移除。
如果需要查看之前的开发文档，可查阅历史提交，尽管我不认为它有参考价值。
当前版本的pilipala已处于维护阶段，预计在2022年推出新的版本。
